name: Build kernel deb packages
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git lsb-release gcc-aarch64-linux-gnu bison flex libelf-dev debhelper bc rsync kmod cpio wget xz-utils patchutils
          sudo timedatectl set-timezone Asia/Jakarta
          sudo hostnamectl set-hostname chewy

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          export LOCALVERSION=
          make LOCALVERSION= mrproper
          make msm8916_defconfig
          make deb-pkg -j"$(($(grep -c processor < /proc/cpuinfo)*2))"

      - name: Prepare artifacts
        run: mkdir artifacts && mv ../linux-image-*.deb ../linux-headers-*.deb artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: artifacts/*

  bootimg:
    name: Make boot images
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        run: |
          sudo apt-get -y update
          sudo apt-get -y install binfmt-support qemu-user-static mkbootimg
          mkdir artifacts

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download kernel
        uses: actions/download-artifact@v4
        with:
          name: kernel
          path: artifacts

      - name: Build
        run: |
          cd .github/scripts
          chmod +x build_boot_img.sh
          sudo ./build_boot_img.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel and boot images
          path: artifacts/*
